### ISSUE TITLE
Which one is your final code?

### ISSUE THREAD

**Issue by zhangl64** [Jason-Yeung33/CPS-888-Software-Engineering#1]
Is this the one:
9adbe85ba9706665ae4c6639ab26575068f4ca22
Thanks.

**Comment by manuelguanipa** [comment]
Hello Professor @zhangl64 ,

Yes, this version of the code is the final one, the other commits are just cleaning/removing unnecessary files we had in our project., but the code will function the same.

Please let me know if you have any questions or concerns.
Thank you,
Manuel Guanipa

**Comment by zhangl64** [comment]
Thanks, @manuelguanipa
